# Generated by Django 2.1.1 on 2018-10-07 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_entry_date_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='date_published',
        ),
    ]
