# Generated by Django 2.1.1 on 2018-10-07 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_entry_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
